apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitness-app-vault-secrets
  namespace: default
spec:
  provider: azure
  secretObjects:                             # Syncs Key Vault data to a native K8s Secret
    - secretName: fitness-app-k8s-secret
      type: Opaque
      data:
        - objectName: mongodb-uri            # Name of the secret inside Azure Key Vault
          key: MONGODB_URI                   # Environment variable key name for your app
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"             # Uses the AKS Node Pool managed identity
    userAssignedIdentityID: "2027386c-9e2d-4db5-b468-f0a9e7410baf" # Replace with your Identity Client ID
    keyvaultName: "sinans-kv"    # Replace with your Key Vault name
    objects: |
      array:
        - |
          objectName: mongodb-uri
          objectType: secret
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"       # Replace with your Azure Tenant ID
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fitness-tracker-app
  namespace: default
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: fitness-tracker-service
      previewService: fitness-tracker-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
    spec:
      containers:
        - name: fitness-tracker-app
          image: pulkit197/fitness_tracker-master-copy3-fitness-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: fitness-app-k8s-secret # Injects secret generated by CSI driver
                  key: MONGODB_URI
            - name: PORT
              value: "5000"
            - name: HOST
              value: "0.0.0.0"
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store" # Required to trigger the CSI fetching logic
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "fitness-app-vault-secrets"
--- 
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
  namespace: default
spec:
  selector:
    app: fitness-tracker-app
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-preview
  namespace: default
spec:
  selector:
    app: fitness-tracker-app
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7-jammy
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
